import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: 'Padma Priya',
  locale: 'en_IN',
  type: 'website',
};

export default function RootLayout({ children }) {
  return ( <html lang='en'>
  <body
    className={`text-text bg-bg scroll-smooth ${inter.className} h-screen overflow-hidden`}
  >
    {children}
  </body>
</html>
);
}

